config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :videos, only: [:index, :new, :create]
  root to: 'videos#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
    user = User.find_or_initialize_by(uid: auth['uid'])
    user.name = auth['info']['name']
    user.token = auth['credentials']['token']
    user.save!
    user
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :file, presence: true
end

app/models/youtube_uploader.rb
class YoutubeUploader
	def initialize(user_token, upload_file_path)
		@user_token = user_token
		@upload_file_path = upload_file_path
	end

	def upload!
		youtube_account.upload_video upload_file_path
	end

	private

		attr_reader :user_token, :upload_file_path

		def youtube_account
			Yt::Account.new access_token: user_token
		rescue Yt::Errors::Unauthorized => e
			e.message
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    flash[:success] = "Welcome, #{user.name}"
    redirect_to root_url
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    @video = Video.new
  end
 
	def create
	  @video = Video.new(video_params)
	  user = User.first
	  upload_file_path = params[:video][:file].tempfile.to_path
	  if @video.valid?
		  begin
		  	uploader = YoutubeUploader.new(YT_CREDENTIAL['yt_token'], upload_file_path)
		  	# uploader = YoutubeUploader.new(user.token, upload_file_path)
		  	uploader.upload!
		  rescue Yt::Errors::Unauthorized => e
		  	flash[:error] = "Can't upload video : #{e.message.split(':').try(:first).strip}. Create new token by login again"
	    	return render :new
		  end
	    flash[:success] = 'Video uploaded!'
	    redirect_to root_url
	  else
	    render :new
	  end
	end
	 
	private
	 
		def video_params
		  params.require(:video).permit(:file)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoUploder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div class="navbar navbar-inverse navbar-fixed-top">

	  <div class="container-fluid">

	    <div class="navbar-header">
	      <%= link_to 'Youtube - API/v3', root_path, class: 'navbar-brand' %>
	    </div>

	    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">
        	<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </button>
      </form>

	    <ul class="nav navbar-nav">
	      <li><%= link_to 'Videos', root_path %></li>
	      <li><%#= link_to 'Login', "/auth/google_oauth2" %></li>
	    </ul>

	  </div>

	  <div class="container-fluid" style="background-color: whitesmoke;">
			<div class='row alertdiv'>
				<% flash.each do |key, value| %>
			    <div>
			      <%= value %>
			    </div>
		  	<% end %>
			</div>
		</div>

	</div>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>
 
    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/videos/index.html.erb
<div class="container-fluid mt-110" style="background-color: beige; margin-bottom: 20px;">
	<div class="row">
		<div class="col-sm-12">
	    <p>
	      <%= link_to 'Upload!', new_video_path, class: 'btn btn-default btn-lg' %>
	    </p>
	  </div>
  </div>
</div>
<div class="container-fluid">
	<div class="row">
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail">
	      <img src="assets/R.jpg" alt="rakesh">
	      <div class="caption">
	        <h3>Thumbnail label</h3>
	        <p>
	        	Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
	        </p>
	        <p>
	        	<a href="#" class="btn btn-primary" role="button">Button</a> 
	        	<a href="#" class="btn btn-default" role="button">Button</a>
	        </p>
	      </div>
	    </div>
	  </div>
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail">
	      <img src="assets/R.jpg" alt="rakesh">
	      <div class="caption">
	        <h3>Thumbnail label</h3>
	        <p>
	        	Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
	        </p>
	        <p>
	        	<a href="#" class="btn btn-primary" role="button">Button</a> 
	        	<a href="#" class="btn btn-default" role="button">Button</a>
	        </p>
	      </div>
	    </div>
	  </div>
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail">
	      <img src="assets/R.jpg" alt="rakesh">
	      <div class="caption">
	        <h3>Thumbnail label</h3>
	        <p>
	        	Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
	        </p>
	        <p>
	        	<a href="#" class="btn btn-primary" role="button">Button</a> 
	        	<a href="#" class="btn btn-default" role="button">Button</a>
	        </p>
	      </div>
	    </div>
	  </div>
	</div>
</div>

app/views/videos/new.html.erb
<div class="container-fluid mt-110">
  <h1>Upload</h1>
 
  <%= form_for @video do |f| %>
    <%= render 'shared/errors', object: @video %>
 
    <div class="form-group">
      <%= f.label :file %>
      <%= f.file_field :file, class: 'form-control', required: true %>
    </div>
 
    <%= f.submit 'Upload video', class: 'btn btn-primary uploadVideo', id: 'uploadVideo'%>
  <% end %>
</div>